# Generated by Django 2.0.2 on 2018-06-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField()),
                ('message', models.CharField(max_length=3000)),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
