# Generated by Django 2.0.2 on 2018-06-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0002_remove_evententry_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='evententry',
            name='created_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
