# Generated by Django 2.0.2 on 2018-06-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivar', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('cellar', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('user_searched', models.CharField(max_length=256)),
                ('wine_id', models.IntegerField()),
            ],
        ),
    ]
