# Generated by Django 2.0.2 on 2018-06-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmodel',
            name='wine_id',
        ),
    ]
