# Generated by Django 2.0.2 on 2018-06-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_searchmodel_wine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmodel',
            name='wine_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
