# Generated by Django 2.0.2 on 2018-06-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winetasting',
            name='location',
            field=models.CharField(default='', max_length=250),
        ),
    ]
