# Generated by Django 2.0.2 on 2018-06-28 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0002_winetasting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winetastinginfo',
            name='cultivar',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='winetastinginfo',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winetasting.WineTasting'),
        ),
    ]
