# Generated by Django 2.0.2 on 2018-07-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0005_auto_20180629_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='WineTastingResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivar', models.CharField(max_length=256)),
                ('wine_code_name', models.CharField(max_length=256)),
                ('total', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'ordering': ('total',),
            },
        ),
    ]
