# Generated by Django 2.0.2 on 2018-07-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0006_winetastingresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='winetastingresults',
            name='user_searched',
            field=models.CharField(default='', max_length=256),
        ),
    ]
