# Generated by Django 2.0.2 on 2018-07-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0009_winetastingfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='winetastingfinal',
            name='cellar',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='winetastingfinal',
            name='real_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
