# Generated by Django 2.0.2 on 2018-07-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0010_auto_20180702_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winetastingfinal',
            name='final_results',
        ),
        migrations.DeleteModel(
            name='WineTastingFinal',
        ),
    ]
