# Generated by Django 2.0.2 on 2018-07-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0011_auto_20180703_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winetastingresults',
            name='user_searched',
        ),
        migrations.AddField(
            model_name='winetastingresults',
            name='cellar',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='winetastingresults',
            name='price',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='winetastingresults',
            name='real_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
