# Generated by Django 2.0.2 on 2018-07-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0013_winetasting_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='winetastingresults',
            name='pics',
            field=models.ImageField(blank=True, null=True, upload_to='wine_pics'),
        ),
    ]
