# Generated by Django 2.0.2 on 2018-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0014_winetastingresults_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='winetastingresults',
            name='relative_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
