# Generated by Django 2.0.2 on 2018-07-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0015_winetastingresults_relative_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winetastingresults',
            name='cellar',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='winetastingresults',
            name='price',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='winetastingresults',
            name='real_name',
            field=models.CharField(max_length=256),
        ),
    ]
