# Generated by Django 2.0.2 on 2018-07-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winetasting', '0016_auto_20180704_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='winetastingresults',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
