# Generated by Django 2.0.2 on 2018-06-20 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='WineInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.ImageField(blank=True, null=True, upload_to='wine_pics')),
                ('name', models.CharField(max_length=256)),
                ('cellar', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('price', models.CharField(max_length=256)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine', to='wineinfo.Cultivar')),
            ],
        ),
    ]
