# Generated by Django 2.0.2 on 2018-06-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wineinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultivar',
            options={'ordering': ('name',)},
        ),
    ]
